name = "letmesee"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
name = "letmesee"

# Staging environment
[env.staging]
name = "letmesee-staging"